### ISSUE TITLE
// is not parsed correctly anymore

### ISSUE THREAD

**Issue by Mouvedia** [badgen/badgen.net#285]
https://badgen.net/badge//subscribe/50AB50?icon=libraries used to work fine, not anymore:
<img alt="libraries.io" src="https://badgen.net/badge//subscribe/50AB50?icon=libraries" />

How to achieve it now? (icon only)

**Comment by Mouvedia** [comment]
I found an alternative [here](https://github.com/badgen/badgen-icons/pull/12#issuecomment-495925508): https:\/\/badgen.net/badge/_/subscribe/50AB50?icon=libraries&label

**Comment by amio** [comment]
It's due to Now platform's change, the [`merge_slashes`](http://nginx.org/en/docs/http/ngx_http_core_module.html#merge_slashes) is set to `on`. Previously this difference only apply to Now v2 (one of reasons blocking Badgen moving to Now v2), now seems they push it to Now v1 too.

@Mouvedia your solution is correct, using `&label` param to override default value with an empty label.
